### ISSUE TITLE
lux.codemirror should emit CodeMirror event with instance, not listen for CodeMirror event

### ISSUE THREAD

**Issue by jeremyherr** [quantmind/lux#132]
In codemirror.js, this line is setting up a listener for the CodeMirror event:
```
scope.$on('CodeMirror', ...
```
This is backwards; it should emit the instance to any listeners. Especially so since it is in a require block and hence loads later than other code. Currently if you want to get the instance you have to wait for a while then broadcast the CodeMirror event with the callback.

**Comment by lsbardel** [comment]
@jeremyherr is this still relevant?

**Comment by jeremyherr** [comment]
@lsbardel Nope, I tested it with the IDE page and now it works as it should.
