### ISSUE TITLE
Multiple select in editig mode

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#148]
The multiple select field does not work properly in editing mode.

The behaviour of the field should be:

* When adding, starts with no selection (unless we have default values)
* When editing, starts with the current values in the field

**Comment by tazo90** [comment]
Here is [branch](https://github.com/tazo90/lux/tree/issue148-multiple-select).

Summary:
- [x] when adding, starts with no selection
- [x] when editing, starts with the current values in the field

There is still one issue with multiple field, not sure if it's a backend issue (this occurs in standard multiple select and ui-select version).
When we try to add another value to an existing non empty field, then we have 500 error.
```
File ".../bmll/env_web/lib/python3.4/site-packages/sqlalchemy/orm/identity.py", line 132, in add
    % (key, ))
AssertionError: A conflicting state is already present in the identity map for key (<class 'lux.extensions.auth.models.Group'>, (11,))
```

To get around this we need to unselect all values (in standard multiple field) or remove all values (in ui-select multiple field).
