### ISSUE TITLE
Intial value not selected in related field selects in forms

### ISSUE THREAD

**Issue by tazo90** [quantmind/lux#154]
There is some trouble because `organisation` field is served from the `api` as json object now.
So we need to parse it [here](https://github.com/quantmind/lux/blob/master/luxjs/services/luxweb.js#L90) to json object.

But some of the fields like `permissions.policy` can't be parse to json object and must be stay as json string, because we want to show it as raw json string e.g. here `/admin/permissions`.

To fill organisation field with initial value again I would need to do something like this in `formReady` function.
```
if (isObject(value)) {
          if (mustBeJsonString) value = JSON.stringify(value, null, 4);
          else {
              var obj = angular.fromJson(value);
              value = obj.repr || obj.id;
          }
}
```

but I'm not sure how to recognize which json field should be parsed to json object and which should stay as json string?

**Comment by jeremyherr** [comment]
The code was stringifying any JSON object form field willy-nilly. But the only reason to stringify a form field that is an Object is if it is meant to be edited as text, i.e. in a textarea. However, this information, provided by the back-end in window.luxforms, is obliterated by the rendering code that creates the form elements. So now I'm caching this information in ```formScope[<formModelName>Type]``` so api.formReady has access to it.

**Comment by tazo90** [comment]
Hi @jeremyherr 
I'm working on this also and seems to be working this:

**luxweb.js**
```
if (isObject(value)) {
      value = angular.fromJson(value);

      // Handles one-to-many field which is serve via json
      if (value.hasOwnProperty('id'))
            value = value.id;
      else
           value = JSON.stringify(value, null, 4);
}
```

**Comment by jeremyherr** [comment]
Sorry, @tazo90,  @reupen asked me to look at it, so I assumed nobody else was working on it. It looks like both of us forgot to assign it to ourselves.

Your solution involves less code, but I like mine better
1. because I wrote it ;)
2. it is more explicit regarding the reason for stringifying an object.Do we really want to blindly pass any object that happens to contain an `id` property to forms?

I'll let @lsbardel decide.

**Comment by tazo90** [comment]
@jeremyherr no problem ;) that's right, your version seems to be less buggy than mine.
