### ISSUE TITLE
UI Select does not pull all data

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#158]
Looks like only the first 25 items are pulled from the backend.
We need a way to pull more when scrolling down (lazily) and we need search facility (which needs backend implementation)

**Comment by tazo90** [comment]
This should be ready:

[Branch](https://github.com/tazo90/lux/tree/issue158-select-enhancements)

Summary:
- [x] server side filtering
- [x] pull more options when scrolling down (lazily) 
- [x] fix bootstrap theme css, choice list should be placed below input search
- [x] fix one-to-many field to display initial value from json data - fixes [https://github.com/quantmind/lux/issues/154](https://github.com/quantmind/lux/issues/154)
