### ISSUE TITLE
Last URL returned by REST APIs is wrong

### ISSUE THREAD

**Issue by reupen** [quantmind/lux#161]
The offset in the URL is past the end of the collection.

**Comment by lsbardel** [comment]
@reupen can you double check the fix is OK?

**Comment by reupen** [comment]
It's still problematic if you pass a custom `offset`. For example. if there are 27 elements in the collection, and you request:

`endpoint_url?limit=5&offset=2`

the last URL returned will be:

`endpoint_url?offset=27&page=2&limit=5` (wrong - will return no items)

**Comment by lsbardel** [comment]
@reupen can you check the new fixes in my previous commit are good?

**Comment by reupen** [comment]
Seems to work, but on the first page `"prev": null` is now returned.

**Comment by lsbardel** [comment]
There is no ``prev`` if it is the first page.

**Comment by lsbardel** [comment]
Right, I see the issue
