### ISSUE TITLE
Ability to configure actions in lux grids

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#178]
Currently lux grids have a button with links for several actions. In addition each row can be edited when clicking on it. We want to be able to configure this behaviour.
For example we may don't want to have the ``add`` action and we may not want to allow ``editing``.

**Comment by tazo90** [comment]
Maybe will be a good idea to add permissions for the specific grid in metadata e.g.
something like this 
```
{can_view: True, can_delete: True, can_edit: False}
```
This gives ability check also user group and grant them specific access to actions.

**Comment by tazo90** [comment]
I made a support to configure grid actions (add, delete, editing) using model permissions.

[Branch](https://github.com/tazo90/lux/tree/issue178-grid-actions)

**Comment by reupen** [comment]
@lsbardel what do you think about @tazo90's question:
> The question is: configuration should be provided via metadata or json options defined in javascript?

Do we want to allow configuration via the metadata API, by options, or both?

**Comment by lsbardel** [comment]
for both really. Metadata will override the options.
@tazo90 your suggestion seems sensible.

**Comment by tazo90** [comment]
I did updates, please inform me if it working as expected.

You can define permissions via metadata (higher priority) or using python views.
The order of apply the permissions in grid according to sources are:
1. `metadata`
2. `python view`
3. `grid defaults`

If permission is not defined then default values for `(UPDATE, CREATE, DELETE)` is `False`.

**Admin views**
```
class UserAdmin(admin.CRUDAdmin):
    permissions = {
        'CREATE': True,
        'UPDATE': False,
        'DELETE': True
    }
```

**Non admin views**
```
permissions = {
    'UPDATE': False,
    ...
}
...
def get_html(self, request):
        app = request.app
        model = self._model
        options = dict(target=model.get_target(request))
        if self.permissions is not None:
            options['permissions'] = self.permissions
        context = {'grid': grid(options)}
        return app.render_template('partials/view.html', context)
```

**Comment by lsbardel** [comment]
released https://github.com/quantmind/lux/releases/tag/0.3.1
