### ISSUE TITLE
CMS - content management system

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#18]
Implement a cms system.

Back-end
* ``Page`` model
* ``Template`` model

Front-end can be built using
* [masonry](http://masonry.desandro.com/) 
* [angular-gridster](https://github.com/ManifestWebDesign/angular-gridster)

Create an angular module to manage the front-end side and the admin editing panel. Angular gridster has [something which we can build on](https://rawgit.com/ManifestWebDesign/angular-gridster/master/index.html#/dashboard).

[octobercms](https://octobercms.com/) looks good and simple.

**Comment by tazo90** [comment]
Here is what I've done so far on the CMS javascript side: [branch](https://github.com/tazo90/lux/tree/cms).

To render the page use directive `<render-page><render-page>`.
It build layout from json, it put `components` inside specific regions.

- [x] Layout and components data are mocked already.
- [x] Render page depending on layout and then render components inside regions.
- [x] One region has many components and has ability to change order of them.
- [x] Change position of images in `imagegallery` component.

**Comment by tazo90** [comment]
- [x] Added API for registering components

**Comment by lsbardel** [comment]
I'm struggling to understand how to use this.

You need add tests for any python line of code you write. This is very important! It helps development and understanding of what does what.

Why did you put `layout_to_html` inside the `AnyPage` Router? A Page model can be associated with any router, not just that one. The function is not very readable and requires more work.

To move forwards quickly:

* Move the `layout_to_html` into the `CMS` class
* Make the function more readable and put information on how the JSON layout should look like to be valid.
* We need some sort of callback for each component, the callbacks registered globally. The reason to have callback, is that some component may be rendered server side.
* Add **tests** to [cms](https://github.com/quantmind/lux/tree/dev/tests/cms) and check coverage

**Comment by tazo90** [comment]
@lsbardel Added fixes:

- [x] Move the `layout_to_html` into the `CMS` class
- [x] Make the function more readable + descriptions
- [ ] Callback for each components
- [x] Add tests
