### ISSUE TITLE
Checkbox rendering

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#195]
The check box is redering inside an input type element.
Why is this the case?
This must be a bug introduced somewhere in the dev process.

**Comment by tazo90** [comment]
The reason of the problem is that a `checkbox` field calls `input renderer` not `checkbox renderer`.

It seems that something has changed the behavior of this.
I will trying to fix this.

**Comment by lsbardel** [comment]
thanks

**Comment by tazo90** [comment]
@lsbardel issue is fixed.
