### ISSUE TITLE
Encode json data in html page

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#202]
Not sure which encoding to use.
The javascript code decodes it.
Not sure what is the best algorithm to use.
Basically we don't want to have these parameters easily readable in the Html page.

**Comment by jeremyherr** [comment]
This does not encrypt it, all it does is make it non-human readable: http://bsonspec.org/#/specification

Looks interesting, but I haven't used it.

**Comment by lsbardel** [comment]
done with base64 encoding
