### ISSUE TITLE
Sidebar still flashes open on admin area pages only

### ISSUE THREAD

**Issue by tomhardman0** [quantmind/lux#237]
Sidebar still flashes off the screen when navigating between pages in the admin area. This has stopped in datasets/tools area.

<img width="329" alt="screen shot 2015-12-16 at 11 11 16" src="https://cloud.githubusercontent.com/assets/9137745/11839469/ed344b68-a3e5-11e5-94dd-e41ff98be17b.png">

**Comment by tomhardman0** [comment]
This bug has been fixed in bmll-portal but would still exist if building on lux from scratch. This will be resolved when we port the existing python css to scss.

**Comment by lsbardel** [comment]
too old
