### ISSUE TITLE
form messages not displayed

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#24]
Form messages from the server are not displayed at field level.
The server returns an object with messages for each field.
These messages should be displayed near the matching form fields

**Comment by tazo90** [comment]
[Branch](https://github.com/tazo90/lux/blob/issue24)

I wonder whether we need commented block of code (line 368) when we get server errors messages now?

**Comment by lsbardel** [comment]
What is the state of this ticket? Did you find the problem?

**Comment by tazo90** [comment]
Yes, issue is done.

**Comment by lsbardel** [comment]
pull request? I cannot see the branch?

**Comment by tazo90** [comment]
Pull request created.

**Comment by lsbardel** [comment]
This works, thanks!
