### ISSUE TITLE
on_request called before on_init 

### ISSUE THREAD

**Issue by jeremyherr** [quantmind/lux#257]
The problem I am having is that I created a subclass of RpcWsMethod, and my `on_request` method is called before `on_init`.

Currently `on_init` is called in the `RpcWsMethod.__init__`
https://github.com/quantmind/lux/blob/master/lux/extensions/sockjs/ws.py#L164

It should be called in `RpcWsCall.__call__`, and that method should wait for it before running `on_request`.
https://github.com/quantmind/lux/blob/master/lux/extensions/sockjs/ws.py#L208

**Comment by lsbardel** [comment]
no longer relevant, the websocket api has changed
