### ISSUE TITLE
strange behavior on last page of grid

### ISSUE THREAD

**Issue by jeremyherr** [quantmind/lux#265]
If you have multiple pages of records in a grid, when you go to the last page, there seem to be more rows than the grid tells you, and you can scroll within the grid to see them although there is no scroll bar. You shouldn't be able to scroll inside the grid.

**Comment by lsbardel** [comment]
I cannot replicate this issue.
The number of rows seems fine and I don't see any scroll bar

**Comment by jeremyherr** [comment]
I can no longer replicate this issue either. I had seen it on the websocket grid I was working on. Possibly it had to do with changes I made?

**Comment by lsbardel** [comment]
Possibly, but it is not an issue of the current grid. Closing
