### ISSUE TITLE
Friendly form message if value exists in the database

### ISSUE THREAD

**Issue by tazo90** [quantmind/lux#31]
When we try create a new object (user, exchanges) and record currently exist in the database then we got `An exception has occurred while evaluating your request.`

From `API` side response is `sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError): 
DETAIL:  Key (symbol)=(fds) exist.`

Would be good to show more friendly message.

**Comment by lsbardel** [comment]
You can uset the ``UniqueField`` validator in the form field.
Check https://github.com/quantmind/lux/blob/dev/tests/odm/__init__.py for an example and tests.
