### ISSUE TITLE
Add actions to admin table

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#35]
In the admin pages we would like to be able to perform actions on selected rows in a grid table.
Think of this actions, as the ones `django` has.

By default a grid should have the `delete items` action for deleting selected items.
An action should also have associated a confirm message if required.
For example, for the `delete items` action, the message should be:
```
Are you sure you want to delete items 4, 7, ...? This cannot be undone!
```

**Comment by lsbardel** [comment]
Actions, should also include, ``add`` to add a new item

**Comment by tazo90** [comment]
@lsbardel Actions have been added: [branch](https://github.com/tazo90/lux/tree/issue35)

**Comment by lsbardel** [comment]
@tazo90 can you setup a live api-portal combo somewhere in the cloud?
You could use sqlite as database if that helps.
It would help while evaluating your implementations

**Comment by tazo90** [comment]
@lsbardel sure, great idea. I'll setup a live api-portal somewhere in the cloud.

**Comment by tazo90** [comment]
@lsbardel done, added notifications. [branch](https://github.com/tazo90/lux/tree/issue35)
