### ISSUE TITLE
Content Model with git backend

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#53]
The idea is to create a ``Content`` rest model with ``git`` backend.
The library to use for git manipulation is either [dulwich](https://www.samba.org/~jelmer/dulwich/docs) or [pygit2](http://www.pygit2.org/).

The development should be in the ``lux.extensions.content`` module of the [dev branch](https://github.com/quantmind/lux/tree/dev/lux/extensions/content)

## Key Points

* We need ``Content`` to behave as close as possible to a database model and therefore to have the basics CRUD operations on the local repository.
* Remote configuration. We want the local repo to have an **optional remote version** (github for example). The remote configuration is useful for background syncing.
* User, which user can access the repo? Does it need to be a special user (`webserver ` for example) which has an account in the remote repository.
* When saving, only commit, no push to remote.

**Comment by SirZazu** [comment]
branch: https://github.com/SirZazu/lux/tree/issue53-content-model

@lsbardel few questions comes to my mind:

1. the Content model should have only one git repository as a backend  and the path for this repo should be in settings? 
2. The files should be considered as "rows" and for example `Content.get('test.md')` should return content of file `test.md` and the `Content.all()` should return list of all files in repository?  
3. Every next file is like new item added to "table" or this should looks different?
4. Is returning content for more then one file possible?
5. How to handle situation when two people are editing the same file at the same time, and  want to write different content? We are using only one branch for this, so what about possible conflicts?

**Comment by lsbardel** [comment]
1. Yes, the `Content` is initialised with a `path` to the repo. The `path` will be coming from settings, still to decide how. We may have more than one Content though! And therefore more than one repo.
2. Both questions Yes, but `Content.get('test')`, the `.md` appended by the backend.
3. Yes, when you create a new entry you must check that it does not exist (Does this answer the question?)
4. Yes, but not important at the moment (therefore skip). We will implement a `query` method where a set of files get be returned.
5. Good point! Same as point 4. We will deal with this in version 2.

very good questions :+1:

**Comment by lsbardel** [comment]
@SirZazu I'm running tests of my mac and they all fails.
```
ERROR: content.models.test_write (tests.content.models.TestContentModel)
----------------------------------------------------------------------
Traceback (most recent call last):

  File "/usr/local/lib/python3.4/site-packages/pulsar/apps/test/runner.py", line 70, in _run_testcls
    yield from self._run(testcls.setUpClass, test_timeout)

  File "/usr/local/lib/python3.4/site-packages/pulsar/apps/test/runner.py", line 102, in _run
    coro = method()

  File "/Users/lsbardel/workspace/lux/tests/content/models.py", line 26, in setUpClass
    init(PWD)

  File "/usr/local/lib/python3.4/site-packages/dulwich/porcelain.py", line 174, in init
    return Repo.init(path)

  File "/usr/local/lib/python3.4/site-packages/dulwich/repo.py", line 887, in init
    cls._init_maybe_bare(controldir, False)

  File "/usr/local/lib/python3.4/site-packages/dulwich/repo.py", line 871, in _init_maybe_bare
    ret.refs.set_symbolic_ref("HEAD", "refs/heads/master")

  File "/usr/local/lib/python3.4/site-packages/dulwich/refs.py", line 539, in set_symbolic_ref
    self._check_refname(name)

  File "/usr/local/lib/python3.4/site-packages/dulwich/refs.py", line 172, in _check_refname
    if not name.startswith(b'refs/') or not check_ref_format(name[5:]):

TypeError: startswith first arg must be str or a tuple of str, not bytes
```
