### ISSUE TITLE
Codemirror integration

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#59]
We would like to use ``codemirror`` as for editing text.
The idea is to decorate a ``TextArea`` with codemirror using a simple angular directive.

We would like to set the language to (default to ``markdown maybe``)

For example (this is just an idea):
```python
class TemplateForm(forms.Form):
    title = forms.CharField()
    body = forms.TextField(textEdit=json.dumps({'language': 'html'}))
```

**Comment by tazo90** [comment]
@lsbardel Codemirror integration is done. [branch](https://github.com/tazo90/lux/tree/issue59-codemirror)

Summary:
- [x] Added support for setup theme
- [x] Added support for setup mode, currently (markdown - default and htmlmixed)

**Comment by lsbardel** [comment]
Right, can you apply the directive to actual forms used by lux?

In particular there are two forms we need:
* [TemplateForm](https://github.com/quantmind/lux/blob/dev/lux/extensions/cms/views.py#L12), **html**
* [PermissionForm](https://github.com/quantmind/lux/blob/dev/lux/extensions/auth/forms.py#L30) **JSON**

You also need to add the theme parameter in the [code extension](https://github.com/tazo90/lux/blob/issue59-codemirror/lux/extensions/code/__init__.py#L30).

Finally, ``CODEMIRROR_MODE`` cannot be passed by lux as a global variable like theme is, since each form may have a different mode. Therefore the mode should be an attribute of the textarea.

**Comment by tazo90** [comment]
Yes, we can apply directive to actual lux forms.

- There is only one javascript file for codemirror, we need to import a separate file for each mode.
- `ngModel` gives ability to pass the `model` to directive and synchronize changes.

**Comment by tazo90** [comment]
@lsbardel I think codemirror integration is done.

Summary:
- [x] Added `text_edit` parameter to the fields in the form with ability to set mode of the editor 
      (`html`, `json`, `markdown`), additionally define editor for following fields:
       - TemplateForm: `body = forms.TextField(text_edit=json.dumps({'mode': 'html'}))`,     
       - PermissionForm: `policy = forms.JsonField(text_edit=json.dumps({'mode': 'json'}))`,
       - TextForm:  `body = forms.TextField(text_edit=json.dumps({'mode': 'markdown'}))`,     
- [x] Removed `CODEMIRROR_MODE` from JS
- [x] Added `CODEMIRROR_THEME` to parameters
- [x] Added tests

**Comment by lsbardel** [comment]
How is codemirror javascript loaded?
The directive should use ``requirejs`` to load the javascript files needed.
Check how the [highlight directive](https://github.com/quantmind/lux/blob/dev/luxjs/blog/highlight.js) does it.

**Comment by tazo90** [comment]
I placed `codemirror-markdown` and `codemirror-htmlmixed` inside `require([])` in `open.js`.

Thanks for the suggestion, 
I'll use approach from `highlight` directive.

**Comment by tazo90** [comment]
- [x] directive use `requirejs` to load the javascript files.

**Comment by lsbardel** [comment]
works
