### ISSUE TITLE
lux.grid $state removal and tests

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#63]
We need tests for the angular grid integration.
At the moment, ``lux.grid`` works only when the ``angular.ui.router`` module is loaded, which is not what we want. We may want to use the grid without angular ``ui.router``.

**Comment by tazo90** [comment]
@lsbardel 

Summary:
- [x] issue fixed (removed $state)
- [ ]  tests has only the skeleton because of problem to run `$lux.api` from `jasmine`

**Comment by lsbardel** [comment]
@tazo90 The grid now works without `ui-router`.
With `ui-router` there are two problems:

* When clicking add, it reload the page to display the form
* Bug when trying to edit a row

**Comment by tazo90** [comment]
@lsbardel thanks for info, I'll fix the issues.

**Comment by tazo90** [comment]
@lsbardel I fixed the first issue, but in the second I noticed that there isn't problem with the `grid` but with `ui-router`. 
When we go immediately to URL e.g. `http://localhost:6060/admin/html_templates/1` we've got error "Error: 'invocables' must be an object", maybe there is a problem in `resolve` method inside `$state`.
