### ISSUE TITLE
lux.grid confirmation panel hide the page

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#65]
The modal overlay is black.
Where does the ``$modal`` service come from?

**Comment by tazo90** [comment]
$modal service come from `angular-strap`, I'll fix it.

**Comment by tazo90** [comment]
Fixed by overwriting a class `.modal-backdrop` in css
```
.modal-backdrop { 
     background: none repeat scroll 0% 0% rgba(0, 0, 0, 0.4); 
}
```
