### ISSUE TITLE
Better implementation of select element in forms

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#67]
The current implementation of a select element, especially with multiple choices, is not great.
There are several open-source options to choose from.

* [ui-select](https://github.com/angular-ui/ui-select)
* [angular strap](http://mgcrea.github.io/angular-strap/#/selects)

**Comment by tazo90** [comment]
Summary
- [x] integration with forms
- [x] choose which widget want to apply for select, `standard` or `ui-select`         
- [x] themes (bootstrap, select2)
- [x] optional filter
- [x] optional search

Fixes:
- [quantmind/lux#67](https://github.com/tazo90/lux/tree/issue67-better-select)

Requires updates on `bmll-portal`:
- [bmlltech/bmll-portal](https://github.com/tazo90/bmll-portal/tree/issue-ui-select)

**Comment by lsbardel** [comment]
Why is the select list on top of the element?
We don't want that really.

<img width="959" alt="screen shot 2015-08-14 at 09 40 40" src="https://cloud.githubusercontent.com/assets/144320/9270342/ee502532-4268-11e5-94a1-d8c5c6d0ec58.png">

**Comment by tazo90** [comment]
This is the problem with `bootstrap` theme (css), we can switch to `select2` theme and then this issue doesn't occur.
