### ISSUE TITLE
Grid panel text overflow

### ISSUE THREAD

**Issue by lsbardel** [quantmind/lux#73]
The text goes outside the panel (see screenshot)

Multiple objects should be listed vertically with a max-height set so that one can scroll to see all elements to be deleted.

In Addition the **This cannot be undone!** message should be on a new line, bold, capital and in red

**DANGER - THIS CANNOT BE UNDONE!**

![image](https://cloud.githubusercontent.com/assets/144320/8621767/51f770d2-271f-11e5-82a4-225f5c820397.png)

**Comment by tazo90** [comment]
@lsbardel issue is [fixed](https://github.com/tazo90/lux/tree/issue73-grid-overflow).
